project_id = "nunwpsiixyqmbgvvokmq"

[functions.create-partner-account]
verify_jwt = false

[functions.create-supplier-account]
verify_jwt = false

[functions.send-shipping-notification]
verify_jwt = false

[functions.setup-supplier-credentials]
verify_jwt = false
